name: Android Release Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Android Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore to root directory
        run: |
          echo "${{ secrets.FEED_FLOW }}" | base64 --decode > feedflow.jks

      - name: Create keystore.properties in root directory
        run: |
          echo "storeFile=feedflow.jks" > keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Debug - Verify keystore files
        run: |
          echo "Contents of keystore.properties:"
          cat keystore.properties
          echo "Keystore file exists:"
          ls -la feedflow.jks

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace --info

      - name: Debug - List build outputs
        run: |
          echo "Build outputs:"
          find app/build/outputs -name "*.apk" -type f
          ls -la app/build/outputs/apk/release/

      - name: Get versionCode from build.gradle.kts
        id: version
        run: |
          VERSION_CODE=$(grep 'versionCode =' app/build.gradle.kts | awk '{print $3}')
          VERSION_NAME=$(grep 'versionName =' app/build.gradle.kts | awk -F'"' '{print $2}')
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Rename APK with versionCode
        run: |
          # Check if signed APK exists first
          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
            mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/FeedFlow_${{ env.VERSION_CODE }}.apk
          elif [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
            echo "Warning: Found unsigned APK, signing configuration may be incorrect"
            mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/FeedFlow_${{ env.VERSION_CODE }}_unsigned.apk
          else
            echo "Error: No APK found in expected location"
            exit 1
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ env.VERSION_NAME }}
          tag_name: ${{ github.ref_name }}
          files: app/build/outputs/apk/release/FeedFlow_${{ env.VERSION_CODE }}.apk

        env:
          GITHUB_TOKEN: ${{ secrets.APP_TOKEN_GITHUB }}